### PR TITLE
Issue #1117: handle race in concurrent bundle split

### LINKED ISSUE #1117: Exception during namespace bundle split
This particular exception was reported. It was during an automatically initiated bundle split. 

```
2018-01-26 00:38:08,489 - ERROR - [pulsar-web-61-28:PulsarWebResource@381] - [null] Failed to validate namespace bundle netflix/prod/ns1/0x84000000_0x86000000
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at org.apache.pulsar.common.naming.NamespaceBundles.validateBundle(NamespaceBundles.java:110)
    at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleRange(PulsarWebResource.java:378)
    at org.apache.pulsar.broker.web.PulsarWebResource.validateNamespaceBundleOwnership(PulsarWebResource.java:404)
    at org.apache.pulsar.broker.admin.Namespaces.splitNamespaceBundle(Namespaces.java:876)
    at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
```

I think that the race condition is happening since all 4 initial bundles are getting split around the same time and the bundle cache gets updated while the new bundle split is being processed. 

The result doesn't cause any particular issue, just that the bundle split fails with invalid bundle range, but the current bundle will continue to run unaffacted until the next split will take place.

### PR DESCRIPTION
**Pull request by zhaijack**
### Motivation

in `NamespaceService.splitAndOwnBundle()`. 
The concurrent update of Policies of same namespace will cause some override to bundles value that kept in Zookeeper. And this involves at least 2 rounds of split. 
e.g.
1. At beginning, we have 2 bundles, with partitions:[0x00000000, 0x7fffffff, 0xffffffff],
2. First round of split: We will split the 2 bundles at the same time. In first bundle split, the `NamespaceBundles` value that returned by `NamespaceBundleFactory.splitBundles()` would be: 
[0x00000000, **0x3fffffff**, 0x7fffffff, 0xffffffff]; 
while at the same time, the `NamespaceBundles` value for second bundle split would be:
 [0x00000000, 0x7fffffff, **0xbfffffff**, 0xffffffff]
3. Then the 2 split operations, whoever success `updateNamespaceBundles` last, will override the former one. 
Here if second split finally success,  it will override the former success value [0x00000000, **0x3fffffff**, 0x7fffffff, 0xffffffff], and the final bundles partitions would be:  [0x00000000, 0x7fffffff, **0xbfffffff**, 0xffffffff];  But we thought it should be [0x00000000, **0x3fffffff**, 0x7fffffff, **0xbfffffff**,  0xffffffff]; 
4. Second round split:  e.g. try to split to range [0x00000000, 0x3fffffff], it will not find upper boundary 0x3fffffff in actual [0x00000000, 0x7fffffff, 0xbfffffff, 0xffffffff].
And  this will cause the error: 
`
java.lang.IllegalArgumentException: Invalid upper boundary for bundle
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
 `
### Modifications

- Add version in NamespaceBundles,  when update the zookeeper z-node, verify the version, and do read-modify-write retry when there are simultaneous write to the z-node.
- Add test for it.

### Result

No user behavior will change. This concurrent bug fixed. 

Fixes #1117

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/LocalZooKeeperCacheService.java [hunk 1]
```diff
@@ -105,6 +108,38 @@ public LocalPolicies deserialize(String path, byte[] content) throws Exception {
 
                 return future;
             }
+
+            @Override
+            public CompletableFuture<Optional<Entry<LocalPolicies, Stat>>> getWithStatAsync(String path) {
```
Comment (rdhabalia) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/LocalZooKeeperCacheService.java]: should we delete `getAsync(String path)` as it has duplicate logic and it is being used by bundle split only?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java [hunk 2]
```diff
@@ -546,87 +546,135 @@ public boolean isNamespaceBundleDisabled(NamespaceBundle bundle) throws Exceptio
...
+            updateFuture.completeExceptionally(new ServiceUnitNotReadyException(msg));
         }
 
-        return unloadFuture.thenApply(res -> {
-            if (!unload) {
-                return null;
+        // If success updateNamespaceBundles, then do invalidateBundleCache and unload.
+        // Else retry splitAndOwnBundleOnceAndRetry.
+        updateFuture.whenCompleteAsync((r, t)-> {
+            if (t != null) {
```
Comment (rdhabalia) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java]: shouldn't we retry only when we get BadVersion error?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java [hunk 3]
```diff
@@ -546,87 +546,135 @@ public boolean isNamespaceBundleDisabled(NamespaceBundle bundle) throws Exceptio
...
+                // retry several times
+                if (counter.decrementAndGet() >= 0) {
+                    pulsar.getOrderedExecutor().submit(
+                        () -> splitAndOwnBundleOnceAndRetry(bundle, unload, counter, unloadFuture));
+                } else {
+                    // Retry enough, fail this.
+                    String msg2 = format("Finish retry, %s not success update nsBundles, reason %S",
```
Comment (rdhabalia) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java]: `reason %s`?

**Comment by zhaijack** [comment]
Thanks @merlimat @rdhabalia for your comments, changed it and rebased to catch up master.

**Comment by merlimat** [comment]
retest this please

**Comment by zhaijack** [comment]
retest this please

**Comment by merlimat** [comment]
@zhaijack Please merge with master that has fix for a very flaky test. 

Also it appears there's a test that might be genuiniley failing: 

https://builds.apache.org/job/pulsar-pull-request/2290/org.apache.pulsar$pulsar-broker/testReport/org.apache.pulsar.broker.service/BrokerServiceTest/testCreateNamespacePolicy/

I don't remember having seen that test failing before.

**Comment by zhaijack** [comment]
@merlimat thanks, will handle it now

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/LocalZooKeeperCacheService.java (hunk 1 above)
Comment (zhaijack) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/LocalZooKeeperCacheService.java]: Thanks, Seems a lot of other place call it indirectly, remove it will cause error of BrokerServiceTest/testCreateNamespacePolicy at least. 
Added it back in latest commit, which removed the duplicated logic.

**Comment by zhaijack** [comment]
@merlimat , test fail because of wrongly removed `getData` in LocalZooKeeperCacheService in commit [2f1e6e1](https://github.com/apache/incubator-pulsar/pull/1428/commits/2f1e6e151add53070249ee628951d2de5d2cfea2), added it back.

**Comment by merlimat** [comment]
retest  this please
