### PR TITLE
Issue 2110: get-retention returns retentionSizeInMB as 0 when set to -1

### LINKED ISSUE #2110: get-retention returns retentionSizeInMB as 0 when set to -1
#### Expected behavior

`retentionSizeInMB` should have a value of -1.

#### Actual behavior

`retentionSizeInMB` is still 0.

#### Steps to reproduce

```bash
# Default is 0 and 0 for size and time.
pulsar-admin namespaces get-retention public/default
# Set to -1 for infinite size and time retention.
pulsar-admin namespaces set-retention public/default --size -1 --time -1
# Get retention again, but size still says 0.
pulsar-admin namespaces get-retention public/default
```

Is this simply a bug in the admin API for reporting the wrong value or is the size retention not being set properly?

#### System configuration
**Pulsar version**: 2.0.1-incubating

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

Fixes #2110. infinite retention is not correctly propagated.

 ### Changes

Fix the command tool to set infinite retention correctly. Update command line description and website to reflect the fact retention size less than 1MB is treated as no retention.

Add an integration test to verify the CLI change works.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java [hunk 1]
```diff
@@ -342,7 +342,7 @@ void run() throws PulsarAdminException {
         private String retentionTimeStr;
 
         @Parameter(names = { "--size", "-s" }, description = "Retention size limit (eg: 10M, 16G, 3T). "
-                + "0 means no retention and -1 means infinite size retention", required = true)
+                + "0 or less than 1MB means no retention and -1 means infinite size retention", required = true)
```
Comment (srkukarni) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java]: This is actually very confusing. Why can't i specify 1kb?

Comment (sijie) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java]: because that is the current logic. the broker only takes MB as inputs. so if you specify less than 1MB, it is 0. This change here is just to update the documentation. we can discuss if we want to change this behavior, which will be a bunch of BC considerations.

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
rerun java8 tests

**Comment by sijie** [comment]
merged as 406f8fa in branch-2.1
