### PR TITLE
Fix #601: Use long when calling curl_easy_getinfo in tests

### LINKED ISSUE #601: Stack overflow during C++ tests
Reproduced locally when compiling on Ubuntu 16.04.

One test is constantly failing and valgrind catches the problem as well: 

```
==670== Memcheck, a memory error detector
==670== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==670== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==670== Command: ./main --gtest_filter=BasicEndToEndTest.testPartitionedProducerConsumer
==670==
log4cxx: Could not read configuration file [log4cxx.conf].
Note: Google Test filter = BasicEndToEndTest.testPartitionedProducerConsumer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BasicEndToEndTest
[ RUN      ] BasicEndToEndTest.testPartitionedProducerConsumer
log4cxx: No appender could be found for logger (pulsar./pulsar/pulsar-client-cpp/lib/ClientImpl.cc).
log4cxx: Please initialize the log4cxx system properly.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8765 (#0)
> PUT /admin/persistent/prop/unit/ns/partition-test/partitions HTTP/1.1
Host: localhost:8765
Accept: */*
Content-Type: application/json
Content-Length: 1

* upload completely sent off: 1 out of 1 bytes
< HTTP/1.1 204 No Content
< Date: Wed, 26 Jul 2017 21:23:46 GMT
< broker-address: localhost
< Server: Jetty(9.3.11.v20160721)
<
* Connection #0 to host localhost left intact
*** stack smashing detected ***: ./main terminated
==670==
==670== Process terminating with default action of signal 6 (SIGABRT)
==670==    at 0x6BA0428: raise (raise.c:54)
==670==    by 0x6BA2029: abort (abort.c:89)
==670==    by 0x6BE27E9: __libc_message (libc_fatal.c:175)
==670==    by 0x6C8411B: __fortify_fail (fortify_fail.c:37)
==670==    by 0x6C840BF: __stack_chk_fail (stack_chk_fail.c:28)
==670==    by 0x4E8E7B: makePutRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (HttpHelper.cc:47)
==670==    by 0x49F3EF: BasicEndToEndTest_testPartitionedProducerConsumer_Test::TestBody() (BasicEndToEndTest.cc:399)
==670==    by 0x52158B: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /pulsar/pulsar-client-cpp/tests/main)
==670==    by 0x51C1BC: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /pulsar/pulsar-client-cpp/tests/main)
==670==    by 0x50148B: testing::Test::Run() (in /pulsar/pulsar-client-cpp/tests/main)
==670==    by 0x501D33: testing::TestInfo::Run() (in /pulsar/pulsar-client-cpp/tests/main)
==670==    by 0x502422: testing::TestCase::Run() (in /pulsar/pulsar-client-cpp/tests/main)
==670==
==670== HEAP SUMMARY:
==670==     in use at exit: 332,376 bytes in 4,737 blocks
==670==   total heap usage: 8,361 allocs, 3,624 frees, 600,439 bytes allocated
==670==
==670== LEAK SUMMARY:
==670==    definitely lost: 0 bytes in 0 blocks
==670==    indirectly lost: 0 bytes in 0 blocks
==670==      possibly lost: 0 bytes in 0 blocks
==670==    still reachable: 332,376 bytes in 4,737 blocks
==670==         suppressed: 0 bytes in 0 blocks
==670== Rerun with --leak-check=full to see details of leaked memory
==670==
==670== For counts of detected and suppressed errors, rerun with: -v
==670== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
./run-unit-tests.sh: line 51:   670 Aborted                 valgrind ./main --gtest_filter=BasicEndToEndTest.testPartitionedProducerConsumer
```

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

As reported in #601, there is a stack overrun in some tests, because `curl_easy_getinfo` expects a `long*` but we're passing an `int*`.

### CODE REVIEW

File: pulsar-client-cpp/tests/HttpHelper.cc [hunk 1]
```diff
@@ -32,16 +32,15 @@ int makePutRequest(const std::string& url, const std::string& body) {
...
     if (res != CURLE_OK) {
         return -1;
     }
 
-    int httpResult = 0;
+    long httpResult = 0;
     curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &httpResult);
     curl_easy_cleanup(curl);
-    return httpResult;
+    return (int) httpResult;
```
Comment (jai1) [inline pulsar-client-cpp/tests/HttpHelper.cc]: How about we change the return type to long, don't like type casting very much.

Comment (merlimat) [inline pulsar-client-cpp/tests/HttpHelper.cc]: HTTP status is anyway typically an `int`. Casting is fine here (just truncates upper 32 bits)
